### ISSUE TITLE
No code of website

### ISSUE THREAD

**Issue by DarshGupta1910** [Learn-Write-Repeat/LWR-WebApp#1]
Hi I'm a participant of Devincept,2021 

I see only a read me file in your repo does that mean contributors have to code from scratch? 

And please tell more about that opportunity you have written in the end. 

Thanks, 
Darsh Gupta

**Comment by dhwaj1902** [comment]
Yes, this project is starting from scratch.
Please read [this](https://github.com/Learn-Write-Repeat/LWR-WebApp#-how-to-contribute-) and to contributing.
