### ISSUE TITLE
Where is the ui

### ISSUE THREAD

**Issue by VenomFate-619** [Learn-Write-Repeat/LWR-WebApp#12]
Is there any wireframe ready, so that we can start with it?

Also summaries the project, UI , schema, functionality

**Comment by dhwaj1902** [comment]
Actually, there is no UI ready right now. We can start with basic ``sign up``, ``sign in``, ``user profile`` pages.

**Comment by VenomFate-619** [comment]
@dhwaj1902 so we can make a basic form and be ready with the logic

**Comment by dhwaj1902** [comment]
Yes we can start with the basic form like email and password. And in profile we can have image, name, theri interests, etc.
