### ISSUE TITLE
Write an express rest api for basic CRUD operations.

### ISSUE THREAD

**Issue by sanyogchangmai** [Learn-Write-Repeat/LWR-WebApp#14]
The projects requires a rest api for the frontend to make requests. Writing a rest api will allow CRUD operations to be performed on the blogs.
Will write a basic rest api for CRUD and later on the rest api can be changed according to the need when authentication and other stuff is implemented. 

- [x] DCP21

**Comment by sanyogchangmai** [comment]
I would like to work on this issue.

**Comment by dhwaj1902** [comment]
ok, @sanyogchangmai seems good to go ahead.
Make sure to add these in schemas:
- title
- description
- thumbnail image

or if you like anything that is more suitable other than these, then add that also.

**Comment by sanyogchangmai** [comment]
@dhwaj1902 I have created a pull request for the issue please review it.
