### ISSUE TITLE
when will be the contributions instructions will be provided? 

### ISSUE THREAD

**Issue by i-priyanshu** [Learn-Write-Repeat/LWR-WebApp#2]

**Comment by dhwaj1902** [comment]
@i-priyanshu please read [this](https://github.com/Learn-Write-Repeat/LWR-WebApp#-how-to-contribute-)

**Comment by swathi-469** [comment]
I would like to work on this issue please assign me...

**Comment by dhwaj1902** [comment]
@swathi-469 sorry but this is not an issue, he is just asking about the code of conduct. If you want to work on any issue then raise that issue and work on it.

**Comment by swathi-469** [comment]
Oh kk thanks for the response
