### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by akshatvirmani** [Learn-Write-Repeat/LWR-WebApp#4]
I would like to make a blogging home page for this project.

**Comment by dhwaj1902** [comment]
Ok @akshatvirmani 
Go ahead with creating a react app and start making a home Page

**Comment by sanyogchangmai** [comment]
If no one is working on this issue can I get this issue assigned?
I can create a react app on the frontend folder.
The sooner we initilize the frontend part the sooner we all can start our contribution to the frontend.

**Comment by dhwaj1902** [comment]
ok, @sanyogchangmai go ahead.

**Comment by sanyogchangmai** [comment]
> ok, @sanyogchangmai go ahead.

Ok

**Comment by akshatvirmani** [comment]
Sir, I am working on the issue. Should I work on it?

**Comment by sanyogchangmai** [comment]
> Sir, I am working on the issue. Should I work on it?

@akshatvirmani I am just creating the react app and once my commits get merged you can work on the home page.

**Comment by sanyogchangmai** [comment]
@dhwaj1902 please have a look I have created a pull request.

**Comment by dhwaj1902** [comment]
> Sir, I am working on the issue. Should I work on it?

@akshatvirmani I have given you the time of one day. You didn't reply back so, I assign it to another person.
And yes as @sanyogchangmai said you can work on the home page.

**Comment by akshatvirmani** [comment]
@dhwaj1902 Ok Sir. I will start working on it.
