### ISSUE TITLE
Create CODE-OF-CONDUCT.md file

### ISSUE THREAD

**Issue by Sitanshu-AI** [Learn-Write-Repeat/LWR-WebApp#5]
i would like to create code of conduct file

**Comment by dhwaj1902** [comment]
Ok @Sitanshu-AI Go Ahead

**Comment by swathi-469** [comment]
If the issue is open , please assign this to me, I am ready with my work

**Comment by dhwaj1902** [comment]
@swathi-469 sorry but there is already a PR raised by @Sitanshu-AI regarding this issue.
