### ISSUE TITLE
Initialize NodeJS.

### ISSUE THREAD

**Issue by dhwaj1902** [Learn-Write-Repeat/LWR-WebApp#9]
Initialize NodeJS server using Node and Express using ``npm init``.

**Comment by i-priyanshu** [comment]
I would like to work on this issue.
Can we use Firebase for authentication?

**Comment by dhwaj1902** [comment]
Yes @i-priyanshu you can work on this issue. 
We can use firebase for authentication, we have to use it as our database, but we are using MongoDB as database.

**Comment by i-priyanshu** [comment]
i can start working on it, if you could assign this issue to me 😄

**Comment by dhwaj1902** [comment]
@i-priyanshu are you working on this issue or will I assign it to another contributor?

**Comment by i-priyanshu** [comment]
yes sir, i am working on it.
